### ISSUE TITLE
Retrieve tags per session?

### ISSUE THREAD

**Issue by cecileherr** [HabitatMap/AirCasting#29]
Is there a way (for someone with near zero programming skills) to retrieve the tags linked to the sessions?

I am using the API through R to retrieve Aircasting data for my local group and I know I can use the tags as a selection criterion, but sometimes it would be much easier to get the tags as a result of the query.

Any suggestion? (if not through the API, maybe through the website, or in files on the phone, or …?)

Thanks in advance!

**Comment by mheimbinder** [comment]
Unfortunately, we had to temporarily disable the API because the number,
frequency, and structure of the calls were paralyzing our web server.
We're working on a fix now and expect the API to be up and working again at
the end of next week.

Thanks for your patience.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap
